source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'trustbadge_iOS_Example', :exclusive => true do
  pod "Trustbadge", :path => "../"
end

target 'trustbadge_iOS_Tests', :exclusive => true do
  pod "Trustbadge", :path => "../"

  pod 'Specta',      '~> 1.0.3'
  pod 'Expecta',     '~> 1.0.2'
  pod 'OCMock',      '~> 3.1.2'
  pod 'OHHTTPStubs', '~> 4.1.0'
end
