source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Trustbadge_Example' do
  pod "Trustbadge", :path => "../"
end

target 'Trustbadge_Tests' do
  pod "Trustbadge", :path => "../"
  
  pod 'Expecta',                 '~> 1.0.2'
  pod 'Expecta+Snapshots',       '~> 3.1.1'
  pod 'FBSnapshotTestCase',      '~> 2.1.1'
  pod 'OCMock',                  '~> 3.4'
  pod 'OHHTTPStubs',             '~> 5.2.3'
  pod 'OHHTTPStubs/HTTPMessage', '~> 5.2.3'
  pod 'Specta',                  '~> 1.0.6'
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ENABLE_BITCODE'] = 'NO'
		end
	end
end
